# Welcome to Drishti's workshop on Machine Learning/ Deep Learning /Computer vision

If you are not familiar with Python Programming language don't worry. Python is one of the easiest computer languages you can learn today and it won't take you long to start writing it yourself! (you would catch up even quicker if you already know a different language like C or javascript or java)

These are excellent python tutorials made by Corey Schafer : 

https://www.youtube.com/watch?v=k9TUPpGqYTo&list=PL-osiE80TeTt2d9bfVyTiXJA-UTHn6WwU&index=2

Watch videos: 2,3,4,5,6,7,8,9,15 to 21.

**Make sure you watch these before proceeding further**.

Feel free to explore python on your own by reading articles about it or watching videos make by other creators. Also don't worry if you don't understand anything at any point. We will be always available to help you. :-)

Now that you have watched these videos lets start with our first library:

PS: feel free to change the values/shapes of any matrix and try to understand what is going on by experimenting! Have fun :)

# NumPy

In machine learning/deep learning/computer vision you will deal a lot with matrices. Large matrices. We are talking about matrices containing millions of elements and multiple axes. And you will have to perform various operations on these, like matrix multiplication, addition, etc. But don't worry Python has you cover here

In [49]:
import numpy

When you ran the above code, you told python to import a library called numpy. Now, NumPy stands for Numerical Python, it is a library made by some brilliant people for the purposes of doing calculations on large matrices effectively. 

Now, here is something that I want you to remember about python. Python is all about doing things that actually matter. In Python we don't believe in reinventing the wheel every time we have to do something. We simply focus on building the best car possible from parts that someone else has already manufactured and optimized. 

So many-a-times in python you will see people "import" various libraries to use the tools created by other people instead of re-writing the code themselves.

Numpy, for example has been written in faster programming languages than python, has been optimized to perfection, is capable of utilizing the multiple cores on you CPU and has an enormous community of people who constantly check for bugs and maintain it. 

Let me give you a quick demo of the power and simplicity of NumPy. Say, you want a matix with 12 rows and 12 columns that contains all zeros. Well using numpy it takes mearly one line!

In [50]:
numpy.zeros((12,12))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

As you can see from running the above code you have a matrix of size (12,12) containing all zeros.

That was fun wasn't it. Alright lets try something new. We are programmers, we are lazy people. We aren't going to count till 12 to check if the above output is actually (12,12). We want numpy to do that too!

So lets run the above code once more but this time we will store the output into a variable.

In [51]:
my_matrix = numpy.zeros((12,12))

Notice how we don't get any output this time. We can see the matrix by printing it:

In [52]:
print(my_matrix)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


Alright, now lets find the shape of `my_matrix`

In [53]:
numpy.shape(my_matrix)

(12, 12)

Yes! It is infact (12,12)

Now, writing `numpy` again and again is tiresome (remember we programmers are lazy people!) so lets rename numpy to something else, something short, like `np`. In python you can do this by making a small change in the import statement:

In [54]:
import numpy as np

Voilà! Now you can simply write `np` in the code instead on `numpy` and everything will work just fine! Lets try it:

In [55]:
np.zeros((12,12))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

Now look, you can name any library anything you want, but there are certain customs we must follow. Kinda like how you can legally name your son anything you want but still you won't name him dummy due to social pressure or something, although it would make a good name, but I digress.

Similarly in python community we have certain customs like, `numpy` should always be imported as `np`. This makes it easier for someone who is looking at your code to understand what is going on.

Alright now that that is out of the way lets have some more fun with numpy and see what it has to offer.

## Converting Python lists to NumPy's Ndarrays

In [56]:
my_list = [[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]] # my list is a python list

In [57]:
my_list

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

Here we have created a list in python. Now whenever we wish to use numpy on python lists we have to convert them into something called an `Ndarray`. We can do this by doing:

In [58]:
ndarray_of_my_list = np.array(my_list)

In [59]:
ndarray_of_my_list

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Hm... It looks the same doesn't it? So what did we actually do? Well lets use the in-build `type` function to check the types of `my_list` and `ndarray_of_my_list`

In [60]:
type(my_list)

list

In [61]:
type(ndarray_of_my_list)

numpy.ndarray

As you can see `ndarray_of_my_list` is in fact different from `my_list` . `my_list` is a simple python `list` whereas `ndarray_of_my_list` is an `ndarray`. Now that we have an ndarray in our hands we can do cool operations on it with the power of NumPy!

## Ndim and Arange

Lets find the dimension of that array!

In [212]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [213]:
np.ndim(a) # np.ndim() gives the dimensions of the array.

2

`a` is a 2-D array.

Lets see some more dimensions. I am going to use `np.arange` function for this. `np.arange` takes the starting value and the ending value and forms an array for us using the values in between.

In [214]:
b = np.arange(1,10)

In [215]:
b # we get an array from 1 to 9. np.array will give values including the first element (here 1) 
  # but excluding the last element (here 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [216]:
np.ndim(b) # as you can see b is a 1-D array

1

What? You say you want an array with values starting from 1 and going till 100 with span of 3?  Well `arange` got you covered!

In [124]:
np.arange(1,100,3) # the third argument tells arange to take steps of 3 instead of the default 1.

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
       52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97])

Lets see some more cool examples:

In [125]:
np.arange(100,1,-1) # go reverse man! take negitive steps

array([100,  99,  98,  97,  96,  95,  94,  93,  92,  91,  90,  89,  88,
        87,  86,  85,  84,  83,  82,  81,  80,  79,  78,  77,  76,  75,
        74,  73,  72,  71,  70,  69,  68,  67,  66,  65,  64,  63,  62,
        61,  60,  59,  58,  57,  56,  55,  54,  53,  52,  51,  50,  49,
        48,  47,  46,  45,  44,  43,  42,  41,  40,  39,  38,  37,  36,
        35,  34,  33,  32,  31,  30,  29,  28,  27,  26,  25,  24,  23,
        22,  21,  20,  19,  18,  17,  16,  15,  14,  13,  12,  11,  10,
         9,   8,   7,   6,   5,   4,   3,   2])

In [126]:
np.arange(1,3,0.01) # baby steps

array([1.  , 1.01, 1.02, 1.03, 1.04, 1.05, 1.06, 1.07, 1.08, 1.09, 1.1 ,
       1.11, 1.12, 1.13, 1.14, 1.15, 1.16, 1.17, 1.18, 1.19, 1.2 , 1.21,
       1.22, 1.23, 1.24, 1.25, 1.26, 1.27, 1.28, 1.29, 1.3 , 1.31, 1.32,
       1.33, 1.34, 1.35, 1.36, 1.37, 1.38, 1.39, 1.4 , 1.41, 1.42, 1.43,
       1.44, 1.45, 1.46, 1.47, 1.48, 1.49, 1.5 , 1.51, 1.52, 1.53, 1.54,
       1.55, 1.56, 1.57, 1.58, 1.59, 1.6 , 1.61, 1.62, 1.63, 1.64, 1.65,
       1.66, 1.67, 1.68, 1.69, 1.7 , 1.71, 1.72, 1.73, 1.74, 1.75, 1.76,
       1.77, 1.78, 1.79, 1.8 , 1.81, 1.82, 1.83, 1.84, 1.85, 1.86, 1.87,
       1.88, 1.89, 1.9 , 1.91, 1.92, 1.93, 1.94, 1.95, 1.96, 1.97, 1.98,
       1.99, 2.  , 2.01, 2.02, 2.03, 2.04, 2.05, 2.06, 2.07, 2.08, 2.09,
       2.1 , 2.11, 2.12, 2.13, 2.14, 2.15, 2.16, 2.17, 2.18, 2.19, 2.2 ,
       2.21, 2.22, 2.23, 2.24, 2.25, 2.26, 2.27, 2.28, 2.29, 2.3 , 2.31,
       2.32, 2.33, 2.34, 2.35, 2.36, 2.37, 2.38, 2.39, 2.4 , 2.41, 2.42,
       2.43, 2.44, 2.45, 2.46, 2.47, 2.48, 2.49, 2.

In [127]:
np.arange(2,1,-0.01) # negitive baby steps!

array([2.  , 1.99, 1.98, 1.97, 1.96, 1.95, 1.94, 1.93, 1.92, 1.91, 1.9 ,
       1.89, 1.88, 1.87, 1.86, 1.85, 1.84, 1.83, 1.82, 1.81, 1.8 , 1.79,
       1.78, 1.77, 1.76, 1.75, 1.74, 1.73, 1.72, 1.71, 1.7 , 1.69, 1.68,
       1.67, 1.66, 1.65, 1.64, 1.63, 1.62, 1.61, 1.6 , 1.59, 1.58, 1.57,
       1.56, 1.55, 1.54, 1.53, 1.52, 1.51, 1.5 , 1.49, 1.48, 1.47, 1.46,
       1.45, 1.44, 1.43, 1.42, 1.41, 1.4 , 1.39, 1.38, 1.37, 1.36, 1.35,
       1.34, 1.33, 1.32, 1.31, 1.3 , 1.29, 1.28, 1.27, 1.26, 1.25, 1.24,
       1.23, 1.22, 1.21, 1.2 , 1.19, 1.18, 1.17, 1.16, 1.15, 1.14, 1.13,
       1.12, 1.11, 1.1 , 1.09, 1.08, 1.07, 1.06, 1.05, 1.04, 1.03, 1.02,
       1.01])

I think you get the point. This is why I love python. You get so much done in just one line !

## Reshape

Awesome! Now lets try to make a 3-D array! 

First lets get a long 1-D array and then lets reshape it to out desired shape

In [102]:
one_d_array = np.arange(0,40)

In [103]:
one_d_array # 0 to 39. (remember 40 is not included!)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

Now lets reshape this. We want there to be 

In [104]:
three_d_array = np.reshape(one_d_array,(10,2,2))

In [105]:
three_d_array

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27]],

       [[28, 29],
        [30, 31]],

       [[32, 33],
        [34, 35]],

       [[36, 37],
        [38, 39]]])

In [108]:
np.shape(three_d_array) # and as you can see reshape reshaped out array into the desired shape!

(10, 2, 2)

In [109]:
np.ndim(three_d_array) # also because our shape has a third value, the output is a 3-D array!

3

## Random

Well arranging values in an order is all well and good but it is kinda boring to be honest..

What if we want a matrix with random values. Lets get a little random shall we! 

In [128]:
np.random.rand(4,5) # np.random.rand will give you a matrix of random values with the shape you asked for(here (4,5))

array([[0.588185  , 0.50257309, 0.32863581, 0.83755947, 0.06493845],
       [0.4163033 , 0.93713403, 0.97006683, 0.32058723, 0.89436321],
       [0.03729683, 0.0353749 , 0.13047742, 0.66781634, 0.02475546],
       [0.63489149, 0.06005054, 0.07483585, 0.58185006, 0.40550644]])

Notice that `np.random.rand` gives random numbers between 0 and 1

You can do the following to get values between 0 and 100:

In [129]:
np.random.rand(4,5)*100

array([[72.64716827, 59.49663531, 97.55988563, 67.99365951, 31.58829944],
       [84.97279895, 68.03025253, 43.15460032, 46.19989441, 13.14493559],
       [90.3638108 ,  8.70850166, 11.25367222, 83.61743694,  9.22984987],
       [61.13509413, 69.41521297, 39.01369306, 68.98204414, 46.62410557]])

Another cool `random` feature (pun unintended):

In [132]:
np.random.randint(5,size=(2,3))

array([[1, 2, 4],
       [1, 0, 4]])

2x3 array with random integers between 0–4

## Sorting a matrix

In [144]:
matrix = np.random.rand(4,5)

In [145]:
matrix

array([[0.73191391, 0.47854694, 0.10491776, 0.45716792, 0.751147  ],
       [0.56976068, 0.84726967, 0.55056362, 0.11734644, 0.07742079],
       [0.2209753 , 0.2036361 , 0.12396266, 0.45086251, 0.29760535],
       [0.69228927, 0.68268921, 0.86286158, 0.50726892, 0.04982218]])

In [181]:
matrix.sort() # sort is inbuild in python. It can sort lists and ndarrays. Notice how it doesn't return anything...

In [147]:
matrix

array([[0.10491776, 0.45716792, 0.47854694, 0.73191391, 0.751147  ],
       [0.07742079, 0.11734644, 0.55056362, 0.56976068, 0.84726967],
       [0.12396266, 0.2036361 , 0.2209753 , 0.29760535, 0.45086251],
       [0.04982218, 0.50726892, 0.68268921, 0.69228927, 0.86286158]])

`sort` will sort a matrix. Notice that in this case the variable `matrix` changes to a sorted form.

`sort` sorts the matrix about the axis -1 by default (here, sorted along rows...). 

You can explicitly tell it sort about 0 (here, along the columns) 

In [150]:
matrix.sort(axis=0)

In [151]:
matrix

array([[0.04982218, 0.11734644, 0.2209753 , 0.29760535, 0.45086251],
       [0.07742079, 0.2036361 , 0.47854694, 0.56976068, 0.751147  ],
       [0.10491776, 0.45716792, 0.55056362, 0.69228927, 0.84726967],
       [0.12396266, 0.50726892, 0.68268921, 0.73191391, 0.86286158]])

## Copying a matrix

In [161]:
matrix = np.random.rand(3,3)*100

In [162]:
matrix

array([[85.57828648, 17.34518996, 91.14556981],
       [66.85216055, 52.80221919, 60.00705157],
       [81.08505721, 78.70477477, 54.03933892]])

As you noticed earlier, when we did `.sort` on a matrix, the values in that matrix got affected. Sometimes we don't want this to happen, we wish to create a copy of the original matrix and work on that instead of affecting the original.

Now there is a catch here, simply doing something as shown below won't work (you might thing you are simply assigning the values in matrix to new_matrix but wait and see):

In [163]:
new_matrix = matrix

Why won't this work? Well lets first check what elements new_matrix has:

In [164]:
new_matrix

array([[85.57828648, 17.34518996, 91.14556981],
       [66.85216055, 52.80221919, 60.00705157],
       [81.08505721, 78.70477477, 54.03933892]])

Now lets try modifying `new_matrix`

In [165]:
new_matrix.sort(axis=-1)

In [166]:
new_matrix

array([[17.34518996, 85.57828648, 91.14556981],
       [52.80221919, 60.00705157, 66.85216055],
       [54.03933892, 78.70477477, 81.08505721]])

And, `new_matrix` is modified, well no surprise there...

But lets check `matrix` once shall we..

In [167]:
matrix

array([[17.34518996, 85.57828648, 91.14556981],
       [52.80221919, 60.00705157, 66.85216055],
       [54.03933892, 78.70477477, 81.08505721]])

Wait what!? `matrix` got sorted too!?? 

Yes. You see when you do `new_matrix = matrix` you are more or less telling python to refer to `matrix` as `new_matrix`. Thats all. It is like renaming your son from dummy to tummy. He is still gonna be your son!

For people who know about some different programming language this is basically `call by reference`

Alright so what should we do now? How should we copy the contents of `matrix` into `new_matrix`. (basically `call by value`)

`np.copy` to the rescue!

In [192]:
matrix = np.random.rand(3,3)*100 # lets get a fresh new matrix to work with
matrix

array([[ 9.92019448, 88.48868193, 59.23585873],
       [20.6288367 , 74.18557337, 64.13928818],
       [33.26881639, 10.80800939,  6.00647136]])

In [193]:
new_matrix = np.copy(matrix)

In [194]:
new_matrix

array([[ 9.92019448, 88.48868193, 59.23585873],
       [20.6288367 , 74.18557337, 64.13928818],
       [33.26881639, 10.80800939,  6.00647136]])

In [195]:
new_matrix.sort() # sort new_matrix

In [196]:
new_matrix # new_matrix sorted along the row

array([[ 9.92019448, 59.23585873, 88.48868193],
       [20.6288367 , 64.13928818, 74.18557337],
       [ 6.00647136, 10.80800939, 33.26881639]])

In [197]:
matrix

array([[ 9.92019448, 88.48868193, 59.23585873],
       [20.6288367 , 74.18557337, 64.13928818],
       [33.26881639, 10.80800939,  6.00647136]])

Look! `matrix` isn't affected. It is like you cloned your son dummy into a completely new being tummy. (You did that to your own son! omg) And now you can safely experiment on your new son tummy. (that analogy went too dark too quickly)

Alright alright I sort of lied to you. You can sort a matrix using `np.sort` instead of python's inbuilt `sort` function. That way you won't actually affect the array you are sorting and will get a new array automatically. (I just wanted to teach you about `call by reference` and `call by value`)

In [198]:
matrix = np.random.rand(3,3)*100 # lets get a fresh new matrix to work with
matrix 

array([[25.65527492, 90.71289465, 66.59066611],
       [ 0.58999069, 57.23829853, 78.34270728],
       [26.38842741, 30.47467435, 77.89283639]])

In [199]:
new_matrix = np.sort(matrix)

In [200]:
new_matrix

array([[25.65527492, 66.59066611, 90.71289465],
       [ 0.58999069, 57.23829853, 78.34270728],
       [26.38842741, 30.47467435, 77.89283639]])

In [201]:
matrix

array([[25.65527492, 90.71289465, 66.59066611],
       [ 0.58999069, 57.23829853, 78.34270728],
       [26.38842741, 30.47467435, 77.89283639]])

Notice how using `np.sort` instead of `sort` didn't affect the original `matrix` and simply returns a sorted `new_matrix`

## Adding and removing elements

In [244]:
my_arr = np.arange(1,10)
my_arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

You can add elements to this array by using the `np.append` function

In [245]:
my_arr = np.append(my_arr,90) # append one to my_arr and store the output in my_arr
my_arr = np.append(my_arr,100)# then append 100 to that
my_arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  90, 100])

Lets say you have 2 arrays. `array1` and `array2`. And you some reason you want to make a bigger array by joining these two arrays together..

In [211]:
array1 = np.random.randint(low = 0,high = 10,size = (10,))# make an array using random integers from [low,high) of size (10,)
array1

array([0, 8, 9, 7, 5, 8, 8, 2, 5, 7])

In [209]:
array2 = np.random.randint(low = 0,high = 10,size = (10,))
array2

array([1, 6, 1, 8, 5, 6, 4, 0, 8, 5])

Using `np.append` you can concatenate the two arrays into one large array

In [210]:
np.append(array1,array2)

array([4, 8, 1, 8, 4, 5, 4, 6, 2, 8, 1, 6, 1, 8, 5, 6, 4, 0, 8, 5])

Lets try this with 2-D arrays

In [220]:
array1 = np.random.randint(low = 0,high = 10,size = (10,10))# make an array using random integers from [low,high) of size (10,10)
array2 = np.random.randint(low = 0,high = 10,size = (10,12))# make an array using random integers from [low,high) of size (10,12)
print('array1\n',array1)
print('array2\n',array2)

array1
 [[6 4 6 5 0 7 1 9 7 4]
 [1 7 4 1 1 9 3 0 5 8]
 [6 1 1 6 4 9 7 2 5 8]
 [0 1 5 7 0 7 2 2 2 5]
 [5 6 0 9 5 5 4 4 4 0]
 [5 7 8 2 1 2 4 2 6 4]
 [3 9 2 2 2 4 9 4 6 0]
 [2 1 7 4 0 5 7 5 7 5]
 [9 7 5 3 5 4 2 9 0 1]
 [5 7 8 0 5 5 0 1 8 7]]
array2
 [[4 9 6 4 3 2 6 2 9 7 5 8]
 [5 8 5 9 2 0 6 1 2 3 8 8]
 [4 5 9 9 5 9 7 6 7 7 2 3]
 [7 0 1 4 4 8 9 8 2 8 6 9]
 [8 1 9 2 2 0 0 2 5 1 2 5]
 [9 7 4 4 9 0 8 9 4 4 5 9]
 [4 5 5 4 7 6 4 2 6 3 6 2]
 [2 0 2 7 1 7 5 2 2 6 2 4]
 [1 3 7 5 8 1 1 7 8 1 6 2]
 [9 7 5 9 0 9 1 8 8 0 7 2]]


In [230]:
np.append(array1,array2) # np.append has axis = None by default. So we get this weird output which is 1-D.

array([6, 4, 6, 5, 0, 7, 1, 9, 7, 4, 1, 7, 4, 1, 1, 9, 3, 0, 5, 8, 6, 1,
       1, 6, 4, 9, 7, 2, 5, 8, 0, 1, 5, 7, 0, 7, 2, 2, 2, 5, 5, 6, 0, 9,
       5, 5, 4, 4, 4, 0, 5, 7, 8, 2, 1, 2, 4, 2, 6, 4, 3, 9, 2, 2, 2, 4,
       9, 4, 6, 0, 2, 1, 7, 4, 0, 5, 7, 5, 7, 5, 9, 7, 5, 3, 5, 4, 2, 9,
       0, 1, 5, 7, 8, 0, 5, 5, 0, 1, 8, 7, 4, 9, 6, 4, 3, 2, 6, 2, 9, 7,
       5, 8, 5, 8, 5, 9, 2, 0, 6, 1, 2, 3, 8, 8, 4, 5, 9, 9, 5, 9, 7, 6,
       7, 7, 2, 3, 7, 0, 1, 4, 4, 8, 9, 8, 2, 8, 6, 9, 8, 1, 9, 2, 2, 0,
       0, 2, 5, 1, 2, 5, 9, 7, 4, 4, 9, 0, 8, 9, 4, 4, 5, 9, 4, 5, 5, 4,
       7, 6, 4, 2, 6, 3, 6, 2, 2, 0, 2, 7, 1, 7, 5, 2, 2, 6, 2, 4, 1, 3,
       7, 5, 8, 1, 1, 7, 8, 1, 6, 2, 9, 7, 5, 9, 0, 9, 1, 8, 8, 0, 7, 2])

In [232]:
np.append(array1,array2,axis=-1) #instead if we give it axis=-1 it concatenates the 2 matrixes along the "column axis"

array([[6, 4, 6, 5, 0, 7, 1, 9, 7, 4, 4, 9, 6, 4, 3, 2, 6, 2, 9, 7, 5, 8],
       [1, 7, 4, 1, 1, 9, 3, 0, 5, 8, 5, 8, 5, 9, 2, 0, 6, 1, 2, 3, 8, 8],
       [6, 1, 1, 6, 4, 9, 7, 2, 5, 8, 4, 5, 9, 9, 5, 9, 7, 6, 7, 7, 2, 3],
       [0, 1, 5, 7, 0, 7, 2, 2, 2, 5, 7, 0, 1, 4, 4, 8, 9, 8, 2, 8, 6, 9],
       [5, 6, 0, 9, 5, 5, 4, 4, 4, 0, 8, 1, 9, 2, 2, 0, 0, 2, 5, 1, 2, 5],
       [5, 7, 8, 2, 1, 2, 4, 2, 6, 4, 9, 7, 4, 4, 9, 0, 8, 9, 4, 4, 5, 9],
       [3, 9, 2, 2, 2, 4, 9, 4, 6, 0, 4, 5, 5, 4, 7, 6, 4, 2, 6, 3, 6, 2],
       [2, 1, 7, 4, 0, 5, 7, 5, 7, 5, 2, 0, 2, 7, 1, 7, 5, 2, 2, 6, 2, 4],
       [9, 7, 5, 3, 5, 4, 2, 9, 0, 1, 1, 3, 7, 5, 8, 1, 1, 7, 8, 1, 6, 2],
       [5, 7, 8, 0, 5, 5, 0, 1, 8, 7, 9, 7, 5, 9, 0, 9, 1, 8, 8, 0, 7, 2]])

You can remove elements using `np.delete`. `np.delete` take the position of the element to be deleted  

In [246]:
array1

array([[6, 4, 6, 5, 0, 7, 1, 9, 7, 4],
       [1, 7, 4, 1, 1, 9, 3, 0, 5, 8],
       [6, 1, 1, 6, 4, 9, 7, 2, 5, 8],
       [0, 1, 5, 7, 0, 7, 2, 2, 2, 5],
       [5, 6, 0, 9, 5, 5, 4, 4, 4, 0],
       [5, 7, 8, 2, 1, 2, 4, 2, 6, 4],
       [3, 9, 2, 2, 2, 4, 9, 4, 6, 0],
       [2, 1, 7, 4, 0, 5, 7, 5, 7, 5],
       [9, 7, 5, 3, 5, 4, 2, 9, 0, 1],
       [5, 7, 8, 0, 5, 5, 0, 1, 8, 7]])

In [250]:
np.delete(array1, (0,0)) # remove element (0,0)

array([4, 6, 5, 0, 7, 1, 9, 7, 4, 1, 7, 4, 1, 1, 9, 3, 0, 5, 8, 6, 1, 1,
       6, 4, 9, 7, 2, 5, 8, 0, 1, 5, 7, 0, 7, 2, 2, 2, 5, 5, 6, 0, 9, 5,
       5, 4, 4, 4, 0, 5, 7, 8, 2, 1, 2, 4, 2, 6, 4, 3, 9, 2, 2, 2, 4, 9,
       4, 6, 0, 2, 1, 7, 4, 0, 5, 7, 5, 7, 5, 9, 7, 5, 3, 5, 4, 2, 9, 0,
       1, 5, 7, 8, 0, 5, 5, 0, 1, 8, 7])

## Slicing and indexing ndarrays

Before reading this make sure you have watched Corey Schafer's video on python list slicing and indexing. Else you won't understand what is going on

https://www.youtube.com/watch?v=ajrtAuDg3yw&list=PL-osiE80TeTt2d9bfVyTiXJA-UTHn6WwU&index=20&t=0s

Also you can read this StackOverflow answer: https://stackoverflow.com/a/509295/11573842 (StackOverflow is a great site meant for developers/coders to ask questions and share problems with other developers/coders and get possible solutions)

You can slice and index ndarrays just like you slice python lists.

In [261]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [262]:
a[0] # get row 0

array([1, 2, 3, 4])

In [263]:
a[0][0] # first get row 0 and then get 0th element in that, here 1

1

In [264]:
a[:,2] # all rows, 3rd column 

array([ 3,  7, 11])

Notice how the result is an ndarray in itself.

Alright, enough NumPy for now. NumPy is a great and extremely useful library which is capable of doing a lot more than what I have shown you. So in you free time try to learn more about it.

# Pandas

Lets start with Pandas now. Here is what the official Pandas site has to say about it:
> Pandas is a fast, powerful, flexible and easy to use open source **data analysis and manipulation** tool,
built on top of the Python programming language. 

Now we are getting into one of the core aspects of data science. Data analysis and data manipulation.