<span style="color:red">**<<<<<<< local**</span>

# Welcome to Drishti's workshop on Machine Learning/ Deep Learning /Computer vision

If you are not familiar with Python Programming language don't worry. Python is one of the easiest computer languages you can learn today and it won't take you long to start writing it yourself! (you would catch up even quicker if you already know a different language like C or javascript or java)

Here are some excellent [python tutorials made by Corey Schafer](https://www.youtube.com/watch?v=k9TUPpGqYTo&list=PL-osiE80TeTt2d9bfVyTiXJA-UTHn6WwU&index=2) in the form of a playlist.

Watch videos: 2,3,4,5,6,7,8,9,15 to 21 of this playlist


**Make sure you watch these before proceeding further (even if you do know some python)**.


Now that you have watched these videos lets start with our first library:

**PS**: Feel free to explore python on your own by reading articles about it or watching videos make by other creators. Also don't worry if you don't understand anything at any point. We will be always available to help you. Also feel free to change the values/shapes of any code you see below and try to understand what is going on by experimenting! Have fun :-)

<span style="color:red">**=======**</span>

# Welcome to Drishti's workshop on Machine Learning/ Deep Learning /Computer vision

If you are not familiar with Python Programming language don't worry. Python is one of the easiest computer languages you can learn today and it won't take you long to start writing it yourself! (you would catch up even quicker if you already know a different language like C or javascript or java)

These are excellent python tutorials made by Corey Schafer : 

https://www.youtube.com/watch?v=k9TUPpGqYTo&list=PL-osiE80TeTt2d9bfVyTiXJA-UTHn6WwU&index=2

Watch videos: 2,3,4,5,6,7,8,9,15 to 21.

**Make sure you watch these before proceeding further**.

Feel free to explore python on your own by reading articles about it or watching videos make by other creators. Also don't worry if you don't understand anything at any point. We will be always available to help you. :-)

Now that you have watched these videos lets start with our first library:

PS: feel free to change the values/shapes of any matrix and try to understand what is going on by experimenting! Have fun :)

<span style="color:red">**>>>>>>> remote**</span>

# NumPy

In machine learning/deep learning/computer vision you will deal a lot with matrices. Large matrices. We are talking about matrices containing millions of elements and multiple axes. And you will have to perform various operations on these, like matrix multiplication, addition, etc. But don't worry Python has you cover here

In [43]:
import numpy

When you ran the above code, you told python to import a library called numpy. Now, NumPy stands for Numerical Python, it is a library made by some brilliant people for the purposes of doing calculations on large matrices effectively. 

Now, here is something that I want you to remember about python. Python is all about doing things that actually matter. In Python we don't believe in reinventing the wheel every time we have to do something. We simply focus on building the best car possible from parts that someone else has already manufactured and optimized. 

So many-a-times in python you will see people "import" various libraries to use the tools created by other people instead of re-writing the code themselves.

Numpy, for example has been written in faster programming languages than python, has been optimized to perfection, is capable of utilizing the multiple cores on you CPU and has an enormous community of people who constantly check for bugs and maintain it. 

Let me give you a quick demo of the power and simplicity of NumPy. Say, you want a matix with 12 rows and 12 columns that contains all zeros. Well using numpy it takes mearly one line!

In [44]:
numpy.zeros((12,12))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

As you can see from running the above code you have a matrix of size (12,12) containing all zeros.

That was fun wasn't it. Alright lets try something new. We are programmers, we are lazy people. We aren't going to count till 12 to check if the above output is actually (12,12). We want numpy to do that too!

So lets run the above code once more but this time we will store the output into a variable.

In [45]:
my_matrix = numpy.zeros((12,12))

Notice how we don't get any output this time. We can see the matrix by printing it:

In [46]:
print(my_matrix)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


Alright, now lets find the shape of `my_matrix`

In [47]:
numpy.shape(my_matrix)

(12, 12)

Yes! It is infact (12,12)

Now, writing `numpy` again and again is tiresome (remember we programmers are lazy people!) so lets rename numpy to something else, something short, like `np`. In python you can do this by making a small change in the import statement:

In [48]:
import numpy as np

Voilà! Now you can simply write `np` in the code instead on `numpy` and everything will work just fine! Lets try it:

In [49]:
np.zeros((12,12))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

Now look, you can name any library anything you want, but there are certain customs we must follow. Kinda like how you can legally name your son anything you want but still you won't name him dummy due to social pressure or something, although it would make a good name, but I digress.

Similarly in python community we have certain customs like, `numpy` should always be imported as `np`. This makes it easier for someone who is looking at your code to understand what is going on.

Alright now that that is out of the way lets have some more fun with numpy and see what it has to offer.

## Converting Python lists to NumPy's Ndarrays

In [50]:
my_list = [[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]] # my list is a python list

In [51]:
my_list

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

Here we have created a list in python. Now whenever we wish to use numpy on python lists we have to convert them into something called an `Ndarray`. We can do this by doing:

In [52]:
ndarray_of_my_list = np.array(my_list)

In [53]:
ndarray_of_my_list

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Hm... It looks the same doesn't it? So what did we actually do? Well lets use the in-build `type` function to check the types of `my_list` and `ndarray_of_my_list`

In [54]:
type(my_list)

list

In [55]:
type(ndarray_of_my_list)

numpy.ndarray

As you can see `ndarray_of_my_list` is in fact different from `my_list` . `my_list` is a simple python `list` whereas `ndarray_of_my_list` is an `ndarray`. Now that we have an ndarray in our hands we can do cool operations on it with the power of NumPy!

## Ndim and Arange

Lets find the dimension of that array!

<span style="color:red">**<<<<<<< local**</span>

In [56]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

<span style="color:red">**=======**</span>

In [212]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

<span style="color:red">**>>>>>>> remote**</span>

In [ ]:
np.ndim(a) # np.ndim() gives the dimensions of the array.

2

`a` is a 2-D array.

Lets see some more dimensions. I am going to use `np.arange` function for this. `np.arange` takes the starting value and the ending value and forms an array for us using the values in between.

In [ ]:
b = np.arange(1,10)

In [ ]:
b # we get an array from 1 to 9. np.array will give values including the first element (here 1) 
  # but excluding the last element (here 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.ndim(b) # as you can see b is a 1-D array

1

What? You say you want an array with values starting from 1 and going till 100 with span of 3?  Well `arange` got you covered!

In [ ]:
np.arange(1,100,3) # the third argument tells arange to take steps of 3 instead of the default 1.

Lets see some more cool examples:

In [ ]:
np.arange(100,1,-1) # go reverse man! take negitive steps

In [ ]:
np.arange(1,3,0.01) # baby steps

In [ ]:
np.arange(2,1,-0.01) # negitive baby steps!

I think you get the point. This is why I love python. You get so much done in just one line !

## Reshape

Awesome! Now lets try to make a 3-D array! 

First lets get a long 1-D array and then lets reshape it to out desired shape

In [65]:
one_d_array = np.arange(0,40)

In [66]:
one_d_array # 0 to 39. (remember 40 is not included!)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

Now lets reshape this. We want there to be 

In [67]:
three_d_array = np.reshape(one_d_array,(10,2,2))

In [68]:
three_d_array

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27]],

       [[28, 29],
        [30, 31]],

       [[32, 33],
        [34, 35]],

       [[36, 37],
        [38, 39]]])

In [69]:
np.shape(three_d_array) # and as you can see reshape reshaped out array into the desired shape!

(10, 2, 2)

In [70]:
np.ndim(three_d_array) # also because our shape has a third value, the output is a 3-D array!

3

## Random

Well arranging values in an order is all well and good but it is kinda boring to be honest..

What if we want a matrix with random values. Lets get a little random shall we! 

In [ ]:
np.random.rand(4,5) # np.random.rand will give you a matrix of random values with the shape you asked for(here (4,5))

Notice that `np.random.rand` gives random numbers between 0 and 1

You can do the following to get values between 0 and 100:

In [ ]:
np.random.rand(4,5)*100

Another cool `random` feature (pun unintended):

In [ ]:
np.random.randint(5,size=(2,3))

2x3 array with random integers between 0–4

## Sorting a matrix

In [ ]:
matrix = np.random.rand(4,5)

In [ ]:
matrix

In [ ]:
matrix.sort() # sort is inbuild in python. It can sort lists and ndarrays. Notice how it doesn't return anything...

In [ ]:
matrix

`sort` will sort a matrix. Notice that in this case the variable `matrix` changes to a sorted form.

`sort` sorts the matrix about the axis -1 by default (here, sorted along rows...). 

You can explicitly tell it sort about 0 (here, along the columns) 

In [ ]:
matrix.sort(axis=0)

In [ ]:
matrix

## Copying a matrix

In [ ]:
matrix = np.random.rand(3,3)*100

In [ ]:
matrix

As you noticed earlier, when we did `.sort` on a matrix, the values in that matrix got affected. Sometimes we don't want this to happen, we wish to create a copy of the original matrix and work on that instead of affecting the original.

Now there is a catch here, simply doing something as shown below won't work (you might thing you are simply assigning the values in matrix to new_matrix but wait and see):

In [ ]:
new_matrix = matrix

Why won't this work? Well lets first check what elements new_matrix has:

In [ ]:
new_matrix

Now lets try modifying `new_matrix`

In [ ]:
new_matrix.sort(axis=-1)

In [ ]:
new_matrix

And, `new_matrix` is modified, well no surprise there...

But lets check `matrix` once shall we..

In [ ]:
matrix

Wait what!? `matrix` got sorted too!?? 

Yes. You see when you do `new_matrix = matrix` you are more or less telling python to refer to `matrix` as `new_matrix`. Thats all. It is like renaming your son from dummy to tummy. He is still gonna be your son!

For people who know about some different programming language this is basically `call by reference`

Alright so what should we do now? How should we copy the contents of `matrix` into `new_matrix`. (basically `call by value`)

`np.copy` to the rescue!

In [ ]:
matrix = np.random.rand(3,3)*100 # lets get a fresh new matrix to work with
matrix

In [ ]:
new_matrix = np.copy(matrix)

In [ ]:
new_matrix

In [ ]:
new_matrix.sort() # sort new_matrix

In [ ]:
new_matrix # new_matrix sorted along the row

In [ ]:
matrix

Look! `matrix` isn't affected. It is like you cloned your son dummy into a completely new being tummy. (You did that to your own son! omg) And now you can safely experiment on your new son tummy. (that analogy went too dark too quickly)

Alright alright I sort of lied to you. You can sort a matrix using `np.sort` instead of python's inbuilt `sort` function. That way you won't actually affect the array you are sorting and will get a new array automatically. (I just wanted to teach you about `call by reference` and `call by value`)

In [ ]:
matrix = np.random.rand(3,3)*100 # lets get a fresh new matrix to work with
matrix 

In [ ]:
new_matrix = np.sort(matrix)

In [ ]:
new_matrix

In [ ]:
matrix

Notice how using `np.sort` instead of `sort` didn't affect the original `matrix` and simply returns a sorted `new_matrix`

## Adding and removing elements

In [ ]:
my_arr = np.arange(1,10)
my_arr

You can add elements to this array by using the `np.append` function

In [ ]:
my_arr = np.append(my_arr,90) # append one to my_arr and store the output in my_arr
my_arr = np.append(my_arr,100)# then append 100 to that
my_arr

Lets say you have 2 arrays. `array1` and `array2`. And you some reason you want to make a bigger array by joining these two arrays together..

In [ ]:
array1 = np.random.randint(low = 0,high = 10,size = (10,))# make an array using random integers from [low,high) of size (10,)
array1

In [ ]:
array2 = np.random.randint(low = 0,high = 10,size = (10,))
array2

Using `np.append` you can concatenate the two arrays into one large array

In [ ]:
np.append(array1,array2)

Lets try this with 2-D arrays

In [ ]:
array1 = np.random.randint(low = 0,high = 10,size = (10,10))# make an array using random integers from [low,high) of size (10,10)
array2 = np.random.randint(low = 0,high = 10,size = (10,12))# make an array using random integers from [low,high) of size (10,12)
print('array1\n',array1)
print('array2\n',array2)

In [ ]:
np.append(array1,array2) # np.append has axis = None by default. So we get this weird output which is 1-D.

In [ ]:
np.append(array1,array2,axis=-1) #instead if we give it axis=-1 it concatenates the 2 matrixes along the "column axis"

You can remove elements using `np.delete`. `np.delete` take the position of the element to be deleted  

In [ ]:
array1

In [ ]:
np.delete(array1, (0,0)) # remove element (0,0)

## Slicing and indexing ndarrays

Before reading this make sure you have watched Corey Schafer's video on python list slicing and indexing. Else you won't understand what is going on

https://www.youtube.com/watch?v=ajrtAuDg3yw&list=PL-osiE80TeTt2d9bfVyTiXJA-UTHn6WwU&index=20&t=0s

Also you can read this StackOverflow answer: https://stackoverflow.com/a/509295/11573842 (StackOverflow is a great site meant for developers/coders to ask questions and share problems with other developers/coders and get possible solutions)

You can slice and index ndarrays just like you slice python lists.

In [ ]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

In [ ]:
a[0] # get row 0

In [ ]:
a[0][0] # first get row 0 and then get 0th element in that, here 1

In [ ]:
a[:,2] # all rows, 3rd column 

Notice how the result is an ndarray in itself.

Alright, enough NumPy for now. NumPy is a great and extremely useful library which is capable of doing a lot more than what I have shown you. So in you free time try to learn more about it.

# Pandas

**A quick reminder**: *make sure you have watched the [5th video]( https://www.youtube.com/watch?v=daefaLgNkw0&list=PL-osiE80TeTt2d9bfVyTiXJA-UTHn6WwU&index=6&t=0s) and [19th video](https://www.youtube.com/watch?v=ajrtAuDg3yw&list=PL-osiE80TeTt2d9bfVyTiXJA-UTHn6WwU&index=19) of the playlist shared above.*

5th video explains about python dictionaries. Pandas dataframes are similar to dictionaries. 19th video explains list slicing which will be useful.

Lets start with Pandas now. Here is what the official Pandas site has to say about it:
> Pandas is a fast, powerful, flexible and easy to use open source **data analysis and manipulation** tool,
built on top of the Python programming language. 

<span style="color:red">**<<<<<<< local**</span>

Now we are getting into one of the core aspects of data science. Data analysis and data manipulation. 

We are going to use this tool to get valuable insight into a developer survey's result.

First lets get our data. Go to this [url](https://insights.stackoverflow.com/survey). Then click on `Download Full Data Set (CSV)` for the **year 2019**. Download the entire folder into the `assets` folder by clicking this button in the left top corner of the screen: ![download button](assets\Images\download.png)This should have downloaded a zip file.

**If you have the appropriate tool to unzip this folder then unzip all its contents it into a folder named `developer_survey_2019` in the `assets` folder. Else run the cell below, it will automatically unzip the ziped folder and save the contents in `developer_survey_2019`. (Make sure that you saved `developer_survey_2019.zip` folder inside the `assets` folder, only then this code will work.)**


**If you have any difficulty in this step contact us immediately as without this you can't proceed any further.**

In [146]:
import os
import errno
import zipfile

path_to_zip_file = 'assets/developer_survey_2019.zip'

if os.path.exists(path_to_zip_file):
    with zipfile.ZipFile(path_to_zip_file, 'r') as zip_ref:
        zip_ref.extractall('assets/developer_survey_2019/')
    assert os.path.exists('assets/developer_survey_2019/')
    print('Unzipped successfully into assets/developer_survey_2019')
else:
    print("Make sure that the zip file has been downloaded to the assets folder other wise this code won't work")
    print("Contact us if you need any help.")
    raise FileNotFoundError(errno.ENOENT, os.strerror(errno.ENOENT), 'developer_survey_2019.zip')

Unzipped successfully into assets/developer_survey_2019


The `developer_survey_2019` folder contains the results of a survey conducted by [StackOverflow](https://en.wikipedia.org/wiki/Stack_Overflow) in the year 2019. 

(If you are interested to know more about this survey read the pdf : `so_survey_2019.pdf` inside `assets/developer_survey_2019`)

Open the folder `developer_survey_2019` and find a file named `survey_results_public.csv`. This is a `csv` file. `csv` stands for `comma separated values`.

>A CSV is a file which allows data to be saved in a tabular format. CSV files can be used with most spreadsheet programs, such as Microsoft Excel or Google Spreadsheets. They differ from other spreadsheet file types because you can only have a single sheet in a file, they can not save cell, column, or row. Also, you cannot not save formulas in this format.

**Why are .CSV files used?**

>These files serve a number of different business purposes. They help companies export a high volume of data to a more concentrated database.

In short: `csv` files are basically excel files with commas instead of cells.

Alright, now try opening the file in excel. You should see something like this:

![csv file](assets\Images\csv.png)

Rows upon rows of tasty data!!

Lets try getting the data from this file this using the pandas library.

## Getting the data

In [111]:
import pandas as pd

In [112]:
df = pd.read_csv("assets/developer_survey_2019/survey_results_public.csv")

In the above line we use `pd.read_csv` to well, read the csv file pointed to by the path : `assets/developer_survey_2019/survey_results_public.csv`. Then we store this into `df`. Now `read_csv` return a pandas dataframe object. 

Lets see what we have inside `df`...

In [113]:
df

Respondent                                         MainBranch Hobbyist  \
0               1             I am a student who is learning to code      Yes   
1               2             I am a student who is learning to code       No   
2               3  I am not primarily a developer, but I write co...      Yes   
3               4                     I am a developer by profession       No   
4               5                     I am a developer by profession      Yes   
...           ...                                                ...      ...   
88878       88377                                                NaN      Yes   
88879       88601                                                NaN       No   
88880       88802                                                NaN       No   
88881       88816                                                NaN       No   
88882       88863                                                NaN      Yes   

                                             OpenSourcer  \
0                                                  Never   
1                                Less than once per year   
2                                                  Never   
3                                                  Never   
4                             Once a month or more often   
...                                                  ...   
88878  Less than once a month but more than once per ...   
88879                                              Never   
88880                                              Never   
88881                                              Never   
88882                            Less than once per year   

                                              OpenSource  \
0      The quality of OSS and closed source software ...   
1      The quality of OSS and closed source software ...   
2      The quality of OSS and closed source software ...   
3      The quality of OSS and closed source software ...   
4      OSS is, on average, of HIGHER quality than pro...   
...                                                  ...   
88878  The quality of OSS and closed source software ...   
88879  The quality of OSS and closed source software ...   
88880                                                NaN   
88881  OSS is, on average, of HIGHER quality than pro...   
88882  OSS is, on average, of HIGHER quality than pro...   

                                              Employment  \
0                 Not employed, and not looking for work   
1                     Not employed, but looking for work   
2                                     Employed full-time   
3                                     Employed full-time   
4                                     Employed full-time   
...                                                  ...   
88878             Not employed, and not looking for work   
88879                                                NaN   
88880                                 Employed full-time   
88881  Independent contractor, freelancer, or self-em...   
88882             Not employed, and not looking for work   

                      Country         Student  \
0              United Kingdom              No   
1      Bosnia and Herzegovina  Yes, full-time   
2                    Thailand              No   
3               United States              No   
4                     Ukraine              No   
...                       ...             ...   
88878                  Canada              No   
88879                     NaN             NaN   
88880                     NaN             NaN   
88881                     NaN             NaN   
88882                   Spain  Yes, full-time   

                                                 EdLevel  \
0                              Primary/elementary school   
1      Secondary school (e.g. American high school, G...   
2               Bachelor’s degree (BA, BS, B.Eng., etc.)   
3               Bachelor’s degree (BA, BS,

Immediately you can start seeing valuable information about your data. 

Look at the first row...

![first row](assets\Images\first_row.png)

This row contains the `features` of you dataframe. While the rest of the rows contain the data corresponding to these features.

Now lets use pandas to get more information about this dataset:

## Exploring the data

In [114]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88883 entries, 0 to 88882
Data columns (total 85 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   Respondent              88883 non-null  int64  
 1   MainBranch              88331 non-null  object 
 2   Hobbyist                88883 non-null  object 
 3   OpenSourcer             88883 non-null  object 
 4   OpenSource              86842 non-null  object 
 5   Employment              87181 non-null  object 
 6   Country                 88751 non-null  object 
 7   Student                 87014 non-null  object 
 8   EdLevel                 86390 non-null  object 
 9   UndergradMajor          75614 non-null  object 
 10  EduOther                84260 non-null  object 
 11  OrgSize                 71791 non-null  object 
 12  DevType                 81335 non-null  object 
 13  YearsCode               87938 non-null  object 
 14  Age1stCode              87634 non-null

Now here is some information we can get from this:
- So df has `88883 rows` and `85 features`. (You can also use `df.shape` to get this exact information)
- We can see the names of all 85 features with info about the datatype of the data within. (Under the `Dtype` column)
    - `int64` indicates that the feature has integer values in it.
    - `float64` indicates that the feature has floating values in it (basically numbers with decimals).
    - `object` indicates that the feature has strings in it. (like : "Not employed, and not looking for work","20s",etc)
- also this line `dtypes: float64(5), int64(1), object(79)` clearly indicates that we have only `5 features with dtype float64`,`1 with dtype int64` and the rest `79 are strings`
- also note the `Non-Null Count` column. It shows how many of the 88883 entries have `NaN` values (`NaN` stands for `Not A Number`. It basically means that this data is missing or is `Null`)

Go back to the `assets\developer_survey_2019` folder. This time open the file named `survey_results_schema.csv` in excel. You should see this:

![csv file](assets\Images\csv2.png)


Clearly this file contains the meaning of all the 85 features. You can go thought them if you are interested.

Now lets get back to our `df`

Instead of printing out the entire `df` everytime we wish to take a peak at it we will use `df.head` function. This allows us to see the "head" of the dataframe. That is the top few items

In [115]:
df.head(7) # show us the first 7 rows. If no aurgument is passed then default = 5

Respondent                                         MainBranch Hobbyist  \
0           1             I am a student who is learning to code      Yes   
1           2             I am a student who is learning to code       No   
2           3  I am not primarily a developer, but I write co...      Yes   
3           4                     I am a developer by profession       No   
4           5                     I am a developer by profession      Yes   
5           6  I am not primarily a developer, but I write co...      Yes   
6           7                     I am a developer by profession       No   

                  OpenSourcer  \
0                       Never   
1     Less than once per year   
2                       Never   
3                       Never   
4  Once a month or more often   
5                       Never   
6                       Never   

                                          OpenSource  \
0  The quality of OSS and closed source software ...   
1  The quality of OSS and closed source software ...   
2  The quality of OSS and closed source software ...   
3  The quality of OSS and closed source software ...   
4  OSS is, on average, of HIGHER quality than pro...   
5  The quality of OSS and closed source software ...   
6  The quality of OSS and closed source software ...   

                                          Employment                 Country  \
0             Not employed, and not looking for work          United Kingdom   
1                 Not employed, but looking for work  Bosnia and Herzegovina   
2                                 Employed full-time                Thailand   
3                                 Employed full-time           United States   
4                                 Employed full-time                 Ukraine   
5                                 Employed full-time                  Canada   
6  Independent contractor, freelancer, or self-em...                 Ukraine   

          Student                                            EdLevel  \
0              No                          Primary/elementary school   
1  Yes, full-time  Secondary school (e.g. American high school, G...   
2              No           Bachelor’s degree (BA, BS, B.Eng., etc.)   
3              No           Bachelor’s degree (BA, BS, B.Eng., etc.)   
4              No           Bachelor’s degree (BA, BS, B.Eng., etc.)   
5              No           Bachelor’s degree (BA, BS, B.Eng., etc.)   
6              No           Bachelor’s degree (BA, BS, B.Eng., etc.)   

                                      UndergradMajor  ...  \
0                                                NaN  ...   
1                                                NaN  ...   
2                      Web development or web design  ...   
3  Computer science, computer engineering, or sof...  ...   
4  Computer science, computer engineering, or sof...  ...   
5                          Mathematics or statistics  ...   
6  Another engineering discipline (ex. civil, ele...  ...   

                             WelcomeChange  \
0  Just as welcome now as I felt last year   
1  Just as welcome now as I felt last year   
2  Just as welcome now as I felt last year   
3  Just as welcome now as I felt last year   
4  Just as welcome now as I felt last year   
5  Just as welcome now as I felt last year   
6    A lot more welcome now than last year   

                                        SONewContent   Age Gender Trans  \
0  Tech articles written by other developers;Indu...  14.0    Man    No   
1  Tech articles written by other developers;Indu...  19.0    Man    No   
2  Tech meetups or events in your area;Courses on...  28.0    Man    No   
3  Tech articles written by other developers;Indu...  22.0    Man    No   
4  Tech meetups or events in your area;Courses on...  30.0    Man    No   
5  Tech articles written by other developers;Indu...  28.0    Man    No   
6                                                NaN  42.0    Man    No

If we are interested in seeing the last few rows we use `df.tail`

In [116]:
df.tail() #default = 5

Respondent MainBranch Hobbyist  \
88878       88377        NaN      Yes   
88879       88601        NaN       No   
88880       88802        NaN       No   
88881       88816        NaN       No   
88882       88863        NaN      Yes   

                                             OpenSourcer  \
88878  Less than once a month but more than once per ...   
88879                                              Never   
88880                                              Never   
88881                                              Never   
88882                            Less than once per year   

                                              OpenSource  \
88878  The quality of OSS and closed source software ...   
88879  The quality of OSS and closed source software ...   
88880                                                NaN   
88881  OSS is, on average, of HIGHER quality than pro...   
88882  OSS is, on average, of HIGHER quality than pro...   

                                              Employment Country  \
88878             Not employed, and not looking for work  Canada   
88879                                                NaN     NaN   
88880                                 Employed full-time     NaN   
88881  Independent contractor, freelancer, or self-em...     NaN   
88882             Not employed, and not looking for work   Spain   

              Student                             EdLevel  \
88878              No           Primary/elementary school   
88879             NaN                                 NaN   
88880             NaN                                 NaN   
88881             NaN                                 NaN   
88882  Yes, full-time  Professional degree (JD, MD, etc.)   

                                          UndergradMajor  ...  \
88878                                                NaN  ...   
88879                                                NaN  ...   
88880                                                NaN  ...   
88881                                                NaN  ...   
88882  Computer science, computer engineering, or sof...  ...   

                                  WelcomeChange  \
88878                                       NaN   
88879                                       NaN   
88880                                       NaN   
88881                                       NaN   
88882  Somewhat less welcome now than last year   

                                            SONewContent   Age Gender Trans  \
88878  Tech articles written by other developers;Tech...   NaN    Man    No   
88879                                                NaN   NaN    NaN   NaN   
88880                                                NaN   NaN    NaN   NaN   
88881                                                NaN   NaN    NaN   NaN   
88882  Tech articles written by other developers;Indu...  18.0    Man    No   

                     Sexuality  \
88878                      NaN   
88879                      NaN   
88880                      NaN   
88881                      NaN   
88882  Straight / Heterosexual   

                                               Ethnicity Dependents  \
88878                                                NaN         No   
88879                                                NaN        NaN   
88880                                                NaN        NaN   
88881                                                NaN        NaN   
88882  Hispanic or Latino/Latina;White or of European...         No   

                SurveyLength SurveyEase  
88878  Appropriate in length       Easy  
88879                    NaN        NaN  
88880                    NaN        NaN  
88881                    NaN        NaN  
88882  Appropriate in length       Easy  

[5 rows x 85 columns]

To see a list of available columns do:

### Basic column and row handling

=> **Column**

In [117]:
df.columns # and just like that you are blessed with 85 feature names!

Index(['Respondent', 'MainBranch', 'Hobbyist', 'OpenSourcer', 'OpenSource',
       'Employment', 'Country', 'Student', 'EdLevel', 'UndergradMajor',
       'EduOther', 'OrgSize', 'DevType', 'YearsCode', 'Age1stCode',
       'YearsCodePro', 'CareerSat', 'JobSat', 'MgrIdiot', 'MgrMoney',
       'MgrWant', 'JobSeek', 'LastHireDate', 'LastInt', 'FizzBuzz',
       'JobFactors', 'ResumeUpdate', 'CurrencySymbol', 'CurrencyDesc',
       'CompTotal', 'CompFreq', 'ConvertedComp', 'WorkWeekHrs', 'WorkPlan',
       'WorkChallenge', 'WorkRemote', 'WorkLoc', 'ImpSyn', 'CodeRev',
       'CodeRevHrs', 'UnitTests', 'PurchaseHow', 'PurchaseWhat',
       'LanguageWorkedWith', 'LanguageDesireNextYear', 'DatabaseWorkedWith',
       'DatabaseDesireNextYear', 'PlatformWorkedWith',
       'PlatformDesireNextYear', 'WebFrameWorkedWith',
       'WebFrameDesireNextYear', 'MiscTechWorkedWith',
       'MiscTechDesireNextYear', 'DevEnviron', 'OpSys', 'Containers',
       'BlockchainOrg', 'BlockchainIs', 'BetterLife'

Now lets try to see only one column of this `dataframe`

In [118]:
df['Country'] # just like dictionaries!

0                United Kingdom
1        Bosnia and Herzegovina
2                      Thailand
3                 United States
4                       Ukraine
                  ...          
88878                    Canada
88879                       NaN
88880                       NaN
88881                       NaN
88882                     Spain
Name: Country, Length: 88883, dtype: object

Doing `df['Country']` shows us only the `Country` column. You can see multiple columns as well by passing them as `list`

In [119]:
df[['Country','Age']]

Country   Age
0              United Kingdom  14.0
1      Bosnia and Herzegovina  19.0
2                    Thailand  28.0
3               United States  22.0
4                     Ukraine  30.0
...                       ...   ...
88878                  Canada   NaN
88879                     NaN   NaN
88880                     NaN   NaN
88881                     NaN   NaN
88882                   Spain  18.0

[88883 rows x 2 columns]

=> **Row**

Now to access a particular row we will use `df.iloc`. `iloc` takes in the index of the row and the index of the column. If the index of the column isn't specified then all columns are included.

In [120]:
df.iloc[0] # get the first row of the df. 0 here is the index of that row

Respondent                                                      1
MainBranch                 I am a student who is learning to code
Hobbyist                                                      Yes
OpenSourcer                                                 Never
OpenSource      The quality of OSS and closed source software ...
                                      ...                        
Sexuality                                 Straight / Heterosexual
Ethnicity                                                     NaN
Dependents                                                     No
SurveyLength                                Appropriate in length
SurveyEase                             Neither easy nor difficult
Name: 0, Length: 85, dtype: object

Like columns you can get multiple rows:

In [121]:
df.iloc[[0,1]] # first 2 rows

Respondent                              MainBranch Hobbyist  \
0           1  I am a student who is learning to code      Yes   
1           2  I am a student who is learning to code       No   

               OpenSourcer                                         OpenSource  \
0                    Never  The quality of OSS and closed source software ...   
1  Less than once per year  The quality of OSS and closed source software ...   

                               Employment                 Country  \
0  Not employed, and not looking for work          United Kingdom   
1      Not employed, but looking for work  Bosnia and Herzegovina   

          Student                                            EdLevel  \
0              No                          Primary/elementary school   
1  Yes, full-time  Secondary school (e.g. American high school, G...   

  UndergradMajor  ...                            WelcomeChange  \
0            NaN  ...  Just as welcome now as I felt last year   
1            NaN  ...  Just as welcome now as I felt last year   

                                        SONewContent   Age Gender Trans  \
0  Tech articles written by other developers;Indu...  14.0    Man    No   
1  Tech articles written by other developers;Indu...  19.0    Man    No   

                 Sexuality Ethnicity Dependents           SurveyLength  \
0  Straight / Heterosexual       NaN         No  Appropriate in length   
1  Straight / Heterosexual       NaN         No  Appropriate in length   

                   SurveyEase  
0  Neither easy nor difficult  
1  Neither easy nor difficult  

[2 rows x 85 columns]

You can get a particular column in these 2 rows too:

In [122]:
df.iloc[[0,1],1] # first 2 rows and column 1 (MainBranch)

0    I am a student who is learning to code
1    I am a student who is learning to code
Name: MainBranch, dtype: object

**Note:** You can also use **`.loc`** in this case. `.iloc` and `.loc` quit are similar. `iloc` is based on `index based slicing` whilst `loc` is based on `label based slicing`. Now beware, `iloc` being `index based` follows python's indexing rules. So when you try something like this: `df.iloc[5:9]` you are selecting rows `[5,9)`, where the last value (`9` in this case) isn't included in the slice. Same example as above but with `.loc`:

In [123]:
df.loc[[0,1],"MainBranch"] # notice the label : MainBranch

0    I am a student who is learning to code
1    I am a student who is learning to code
Name: MainBranch, dtype: object

**value_counts**

Now lets try to explore the data a bit by using the `value_counts` method/function.

In [124]:
df['Country'].value_counts()

United States                       20949
India                                9061
Germany                              5866
United Kingdom                       5737
Canada                               3395
                                    ...  
Chad                                    1
Niger                                   1
Sao Tome and Principe                   1
Saint Vincent and the Grenadines        1
Dominica                                1
Name: Country, Length: 179, dtype: int64

And just like that we know that this site is popular amongst people from United States,India,Germany,United Kingdom and Canada.

### Filtering

I want to show you something.. run the cell below:

In [125]:
df['Gender']=='Man'

0         True
1         True
2         True
3         True
4         True
         ...  
88878     True
88879    False
88880    False
88881    False
88882     True
Name: Gender, Length: 88883, dtype: bool

Notice how this results in a long column of True/False values? Alright run the following cell too:

<span style="color:red">**=======**</span>

Now we are getting into one of the core aspects of data science. Data analysis and data manipulation.

<span style="color:red">**>>>>>>> remote**</span>