# Hello there. This is a Jupyter notebook 

The cells below contain python code. When you click on a cell it gets selected. Then you can click on the ">|" (run) button on the top to run that cell

## add explaination about jupyter notebook and how to run stuff...

# NumPy

In machine learning/deep learning/computer vision you will deal a lot with matrices. Large matrices. We are talking about matrices containing millions of elements and multiple axes. And you will have to perform various operations on these, like matrix multiplication, addition, etc. But don't worry Python has you cover here

In [49]:
import numpy

When you ran the above code, you told python to import a library called numpy. Now, NumPy stands for Numerical Python, it is a library made by some brilliant people for the purposes of doing calculations on large matrices effectively. 

Now, here is something that I want you to remember about python. Python is all about doing things that actually matter. In Python we don't believe in reinventing the wheel every time we have to do something. We simply focus on building the best car possible from parts that someone else has already manufactured and optimized. 

So many-a-times in python you will see people "import" various libraries to use the tools created by other people instead of re-writing the code themselves.

Numpy, for example has been written in faster programming languages than python, has been optimized to perfection, is capable of utilizing the multiple cores on you CPU and has an enormous community of people who constantly check for bugs and maintain it. 

Let me give you a quick demo of the power and simplicity of NumPy. Say, you want a matix with 12 rows and 12 columns that contains all zeros. Well using numpy it takes mearly one line!

In [50]:
numpy.zeros((12,12))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

As you can see from running the above code you have a matrix of size (12,12) containing all zeros.

That was fun wasn't it. Alright lets try something new. We are programmers, we are lazy people. We aren't going to count till 12 to check if the above output is actually (12,12). We want numpy to do that too!

So lets run the above code once more but this time we will store the output into a variable.

In [51]:
my_matrix = numpy.zeros((12,12))

Notice how we don't get any output this time. We can see the matrix by printing it:

In [52]:
print(my_matrix)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


Alright, now lets find the shape of `my_matrix`

In [53]:
numpy.shape(my_matrix)

(12, 12)

Yes! It is infact (12,12)

Now, writing `numpy` again and again is tiresome (remember we programmers are lazy people!) so lets rename numpy to something else, something short, like `np`. In python you can do this by making a small change in the import statement:

In [54]:
import numpy as np

Voilà! Now you can simply write `np` in the code instead on `numpy` and everything will work just fine! Lets try it:

In [55]:
np.zeros((12,12))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

Now look, you can name any library anything you want, but there are certain customs we must follow. Kinda like how you can legally name your son anything you want but still you won't name him dummy due to social pressure or something, although it would make a good name, but I digress.

Similarly in python community we have certain customs like, `numpy` should always be imported as `np`. This makes it easier for someone who is looking at your code to understand what is going on.

Alright now that that is out of the way lets have some more fun with numpy and see what it has to offer.

## Converting Python lists to NumPy's Ndarrays

In [56]:
my_list = [[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]] # my list is a python list

In [57]:
my_list

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

Here we have created a list in python. Now whenever we wish to use numpy on python lists we have to convert them into something called an `Ndarray`. We can do this by doing:

In [58]:
ndarray_of_my_list = np.array(my_list)

In [59]:
ndarray_of_my_list

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Hm... It looks the same doesn't it? So what did we actually do? Well lets use the in-build `type` function to check the types of `my_list` and `ndarray_of_my_list`

In [60]:
type(my_list)

list

In [61]:
type(ndarray_of_my_list)

numpy.ndarray

As you can see `ndarray_of_my_list` is in fact different from `my_list` which is simple python list. Now that we have an ndarray in our hands we can do cool operations on it with the power of NumPy!

## Ndim and Arange

Lets find the dimension of that array!

In [62]:
a = ndarray_of_my_list # assigning ndarray_of_my_list to a. Too hard to type!

In [63]:
np.ndim(a) # np.ndim() gives the dimensions of the array.

2

`a` is a 2-D array.

Lets see some more dimensions. I am going to use `np.arange` function for this. `np.arange` takes the starting value and the ending value and forms an array for us using the values in between.

In [64]:
b = np.arange(1,10)

In [65]:
b # we get an array from 1 to 9. np.array will give values including the first element (here 1) 
  # but excluding the last element (here 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
np.ndim(b) # as you can see b is a 1-D array

1

## Reshape

Awesome! Now lets try to make a 3-D array! 

First lets get a long 1-D array and then lets reshape it to out desired shape

In [102]:
one_d_array = np.arange(0,40)

In [103]:
one_d_array # 0 to 39. (remember 40 is not included!)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

Now lets reshape this. We want there to be 

In [104]:
three_d_array = np.reshape(one_d_array,(10,2,2))

In [105]:
three_d_array

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27]],

       [[28, 29],
        [30, 31]],

       [[32, 33],
        [34, 35]],

       [[36, 37],
        [38, 39]]])

In [108]:
np.shape(three_d_array) # and as you can see reshape reshaped out array into the desired shape!

(10, 2, 2)

In [109]:
np.ndim(three_d_array) # also because our shape has a third value, the output is a 3-D array!

3